version: '3.8'

services:
  # MariaDB Database
  database:
    image: mariadb:10.11
    container_name: wakanda_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: wakanda_db
      MYSQL_USER: vundla
      MYSQL_PASSWORD: "Mv@20217$"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - wakanda_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 5s
      retries: 3

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wakanda_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+pymysql://vundla:Mv@20217$@database:3306/wakanda_db
      SECRET_KEY: production-secret-key-change-this
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      ENVIRONMENT: production
      DEBUG: false
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
    networks:
      - wakanda_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: wakanda_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wakanda_network
    command: redis-server --appendonly yes

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: wakanda_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - wakanda_network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

networks:
  wakanda_network:
    driver: bridge